from core.world.entities.world.season_types import SeasonTypes
from core.world.utils.size import Size

BACKUP_EVERY_STEP = 1000

STEP_TIME = 1

STEPS_IN_YEAR = 100000
SPRING_START_YEAR_STEP = 0
SUMMER_START_YEAR_STEP = 15000
AUTUMN_START_YEAR_STEP = 75000
WINTER_START_YEAR_STEP = 90000

COLD_DAMAGE = 10
OFFENSIVE_OPERATION_RELATION_COST = 5000
HUNGER_THRESHOLD_PERCENTAGE = 50
CALORIES_RESERVE_STEPS = 500

MAX_DISTANCE_TO_SUB_NEST = 400
MAX_DISTANCE_TO_OPERATION_TARGET = 1500
MAX_SUB_NEST_COUNT = 100
FOOD_IN_NEW_COLONY_MAIN_NEST = 99999999

MAX_NAME_LENGTH = 50
MIN_NAME_LENGTH = 3

NEW_WORLD_GENERATING_CHUNKS_HORIZONTAL = 10
NEW_WORLD_GENERATING_CHUNKS_VERTICAL = 10

PERFORMANCE_TEST_COLONY_POPULATION = 20

ITEM_SOURCE_BLOCKING_RADIUS = 100
NEST_BLOCKING_RADIUS = 50
GENERATING_CHUNK_SIZE = Size(1000, 1000)
MAP_CHUNK_SIZE = Size(500, 500)
VIEW_CHUNK_SIZE = Size(1000, 1000)
NEST_AREA = 300

NUPTIAL_FLIGHT_SEASONS = [SeasonTypes.SUMMER, SeasonTypes.AUTUMN]

NUPTIAL_MALES_GENRERATE_COUNT = 3
NUPT_MALE_MUTATITON_PERCENT = 10
NUPT_MALE_SUPER_MUTATION_CHANCE_PERCENT = 10
NUPT_MALE_SUPER_MUTATION_PERCENT = 20
NUPT_MALE_PROBABILITY_OF_SUPER_GENE = 90
NUPT_MALE_SUPER_GENE_UPGRADE_MULTIPLIER = 1.5
NUPT_MALE_SUPER_GENE_THRESHOLD_BODY_STRENGTH = 100
NUPT_MALE_SUPER_GENE_THRESHOLD_BODY_DEFENSE = 200
NUPT_MALE_SUPER_GENE_THRESHOLD_SPECIALIZATION_BUILDING_SUBNEST = 100
NUPT_MALE_SUPER_GENE_THRESHOLD_ADAPTATION_COLD = 30

ANTARA_MUTATITON_PERCENT = 5
ANTARA_SUPER_MUTATION_CHANCE_PERCENT = 0
ANTARA_SUPER_MUTATION_PERCENT = 0

BASE_ADAPTATION_APPETITE_MULTIPLIER = 1
BASE_ADAPTATION_DEVELOPMENT_APPETITE_MULTIPLIER = 1
BASE_ADAPTATION_COLD_RESISTANCE_POINTS = 80 # 0 degrees Celsius
BASE_BODY_DEFENSE = 10
BASE_BODY_HP_REGEN_RATE = 3
BASE_BODY_LIFE_SPAN = STEPS_IN_YEAR * 2
BASE_BODY_MAX_HP = 100
BASE_BODY_SIGHT_DISTANCE = 200
BASE_BODY_SPEED = 32
BASE_BODY_STRENGTH = 20
BASE_DEVELOPMENT_MALE_STRENGTH = 0.8
BASE_DEVELOPMENT_MALE_DEFENSE = 0.8
BASE_DEVELOPMENT_MALE_MAX_HP = 0.8
BASE_DEVELOPMENT_MALE_HP_REGEN_RATE = 0.8
BASE_DEVELOPMENT_MALE_SPEED = 1
BASE_DEVELOPMENT_MALE_LIFE_SPAN = 0.5
BASE_DEVELOPMENT_QUEEN_STRENGTH = 1.2
BASE_DEVELOPMENT_QUEEN_DEFENSE = 1.5
BASE_DEVELOPMENT_QUEEN_MAX_HP = 1.5
BASE_DEVELOPMENT_QUEEN_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_QUEEN_SPEED = 0.5
BASE_DEVELOPMENT_QUEEN_LIFE_SPAN = 10
BASE_DEVELOPMENT_WARRIOR_STRENGTH = 1.2
BASE_DEVELOPMENT_WARRIOR_DEFENSE = 1.5
BASE_DEVELOPMENT_WARRIOR_MAX_HP = 1.5
BASE_DEVELOPMENT_WARRIOR_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_WARRIOR_SPEED = 1
BASE_DEVELOPMENT_WARRIOR_LIFE_SPAN = 1
BASE_DEVELOPMENT_WORKER_STRENGTH = 1
BASE_DEVELOPMENT_WORKER_DEFENSE = 1
BASE_DEVELOPMENT_WORKER_MAX_HP = 1
BASE_DEVELOPMENT_WORKER_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_WORKER_SPEED = 1
BASE_DEVELOPMENT_WORKER_LIFE_SPAN = 1

NEW_SPECIE_MUTATION_PERCENT = 10
NEW_SPECIE_SUPER_MUTATE_CHANCE = 10
NEW_SPECIE_SUPER_MUTATE_PERCENT = 20

MAX_BODY_SIGHT_DISTANCE = 250
MIN_BODY_SIGHT_DISTANCE = 50
MAX_BODY_SPEED = 64
MIN_BODY_SPEED = 10

NEW_EGG_FOOD_COST = 100
LAY_EGG_SEASONS = [SeasonTypes.SUMMER]
EGG_PROGRESS_PER_STEP = 1

LARVA_FEED_PORTION_SIZE = 1
LARVA_REQUIRED_FOOD_QUEEN_MULTIPLIER = 3
LARVA_REQUIRED_FOOD_WARRIOR_MULTIPLIER = 2
LARVA_REQUIRED_FOOD_WORKER_MULTIPLIER = 1
LARVA_REQUIRED_FOOD_MALE_MULTIPLIER = 0.8
LARVA_REQUIRED_FOOD_COMMON_MULTIPLIER = 10

HONEYDEW_ITEM_SOURCE_MAX_FERTILITY = 90
HONEYDEW_ITEM_SOURCE_MIN_FERTILITY = 50
HONEYDEW_ITEM_SOURCE_MAX_ITEM_STRENGTH = 180
NECTAR_ITEM_SOURCE_MAX_FERTILITY = 70
NECTAR_ITEM_SOURCE_MIN_FERTILITY = 40
NECTAR_ITEM_SOURCE_MAX_ITEM_STRENGTH = 140

BUG_CORPSE_MIN_STRENGTH = 10000
BUG_CORPSE_MAX_STRENGTH = 50000
BUG_CORPSE_SPAWN_STEP_FREQUENCY = 1000
SPAWN_BUG_CORPSES = True
BUG_CORPSE_SPAWN_SEASONS = [SeasonTypes.SUMMER, SeasonTypes.AUTUMN]

LADYBUG_COLONY_ID = 1
MIN_LADYBUG_COUNT = 3
ANTS_PER_LADYBUG = 1
LADYBUG_SPAWN_STEP_FREQUENCY = 500
SPAWN_LADYBUGS = True
LADYBUG_SPAWN_SEASONS = [SeasonTypes.SPRING, SeasonTypes.SUMMER]

ANT_TRANSPORT_NEST_FOOD_CAPACITY = 1000

BUG_CORPSE_ITEM_LIFE_SPAN = 500
FLOWER_ITEM_LIFE_SPAN = 500
LEAF_ITEM_LIFE_SPAN = 70
HONEYDEW_ITEM_LIFE_SPAN = 15
NECTAR_ITEM_LIFE_SPAN = 15
ANT_FOOD_ITEM_LIFE_SPAN = 20
STICK_ITEM_LIFE_SPAN = 70
MIN_LEAF_ITEM_AREA_FERTILITY = 1
MAX_LEAF_ITEM_AREA_FERTILITY = 5
MIN_STICK_ITEM_AREA_FERTILITY = 1
MAX_STICK_ITEM_AREA_FERTILITY = 4
MIN_FLOWER_ITEM_AREA_FERTILITY = 1
MAX_FLOWER_ITEM_AREA_FERTILITY = 4
