from core.world.entities.world.season_types import SeasonTypes

WORLD_ID = 1
STEP_TIME = 1
LADYBUG_COLONY_ID = 1
ANT_COLONY_ENEMIES_IDS = [LADYBUG_COLONY_ID]
COLD_DAMAGE = 10
MAX_ATTACK_DISTANCE = 50
NEW_EGG_FOOD_COST = 100
NEST_MAX_NOT_BUILDING_STEPS = 100
STEPS_IN_YEAR = 100
SPRING_START_YEAR_STEP = 0
SUMMER_START_YEAR_STEP = 20
AUTUMN_START_YEAR_STEP = 60
WINTER_START_YEAR_STEP = 80
PROBABILITY_OF_SUPER_GENE = 100
MUTATITON_PERCENT = 15
SUPER_MUTATION_CHANCE_PERCENT = 10
SUPER_MUTATION_PERCENT = 40
SUPER_GENE_THRESHOLD_BODY_STRENGTH = 1000
SUPER_GENE_THRESHOLD_BODY_DEFENSE = 1000
SUPER_GENE_THRESHOLD_BUILDING_SUBNEST = 1000
SUPER_GENE_THRESHOLD_ADAPTATION_COLD = 200
SUPER_GENE_UPGRADE_MULTIPLIER = 80
OFFENSIVE_OPERATION_RELATION_COST = 500
ANTS_PER_LADYBUG = 10
LAY_EGG_SEASONS = [SeasonTypes.SUMMER]