from core.world.entities.world.season_types import SeasonTypes
from core.world.utils.size import Size

STEP_TIME = 1
LADYBUG_COLONY_ID = 1

STEPS_IN_YEAR = 10000
SPRING_START_YEAR_STEP = 0
SUMMER_START_YEAR_STEP = 400
AUTUMN_START_YEAR_STEP = 6000
WINTER_START_YEAR_STEP = 8000

ANTS_PER_LADYBUG = 10
SPAWN_LADYBUGS = False
SPAWN_BUG_CORPSES = False

COLD_DAMAGE = 10
OFFENSIVE_OPERATION_RELATION_COST = 500
HUNGER_THRESHOLD_PERCENTAGE = 50
CALORIES_RESERVE_STEPS = 500
MAX_DISTANCE_TO_SUB_NEST = 400
MAX_DISTANCE_TO_OPERATION_TARGET = 1500
MAX_SUB_NEST_COUNT = 5
FOOD_IN_NEW_COLONY_MAIN_NEST = 99999999

MAX_NAME_LENGTH = 50
MIN_NAME_LENGTH = 3

ITEM_SOURCE_BLOCKING_RADIUS = 70
NEST_BLOCKING_RADIUS = 50
GENERATING_CHUNK_SIZE = Size(1000, 1000)
MAP_CHUNK_SIZE = Size(500, 500)
VIEW_CHUNK_SIZE = Size(1000, 1000)
NEST_AREA = 300

NUPTIAL_FLIGHT_SEASONS = [SeasonTypes.SUMMER, SeasonTypes.AUTUMN]

NUPTIAL_MALES_GENRERATE_COUNT = 3
NUPT_MALE_MUTATITON_PERCENT = 10
NUPT_MALE_SUPER_MUTATION_CHANCE_PERCENT = 10
NUPT_MALE_SUPER_MUTATION_PERCENT = 20
NUPT_MALE_PROBABILITY_OF_SUPER_GENE = 50
NUPT_MALE_SUPER_GENE_UPGRADE_MULTIPLIER = 1.5
NUPT_MALE_SUPER_GENE_THRESHOLD_BODY_STRENGTH = 1000
NUPT_MALE_SUPER_GENE_THRESHOLD_BODY_DEFENSE = 1000
NUPT_MALE_SUPER_GENE_THRESHOLD_SPECIALIZATION_BUILDING_SUBNEST = 1000
NUPT_MALE_SUPER_GENE_THRESHOLD_ADAPTATION_COLD = 200

ANTARA_MUTATITON_PERCENT = 5
ANTARA_SUPER_MUTATION_CHANCE_PERCENT = 0
ANTARA_SUPER_MUTATION_PERCENT = 0

BASE_ADAPTATION_APPETITE_MULTIPLIER = 1
BASE_ADAPTATION_DEVELOPMENT_APPETITE_MULTIPLIER = 1
BASE_ADAPTATION_COLD_RESISTANCE_POINTS = 80 # 0 degrees Celsius
BASE_BODY_DEFENSE = 5
BASE_BODY_HP_REGEN_RATE = 5
BASE_BODY_LIFE_SPAN = STEPS_IN_YEAR * 2
BASE_BODY_MAX_HP = 100
BASE_BODY_SIGHT_DISTANCE = 200
BASE_BODY_SPEED = 32
BASE_BODY_STRENGTH = 10
BASE_DEVELOPMENT_MALE_STRENGTH = 0.8
BASE_DEVELOPMENT_MALE_DEFENSE = 0.8
BASE_DEVELOPMENT_MALE_MAX_HP = 0.8
BASE_DEVELOPMENT_MALE_HP_REGEN_RATE = 0.8
BASE_DEVELOPMENT_MALE_SPEED = 1
BASE_DEVELOPMENT_MALE_LIFE_SPAN = 0.5
BASE_DEVELOPMENT_QUEEN_STRENGTH = 1.2
BASE_DEVELOPMENT_QUEEN_DEFENSE = 1.5
BASE_DEVELOPMENT_QUEEN_MAX_HP = 1.5
BASE_DEVELOPMENT_QUEEN_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_QUEEN_SPEED = 0.5
BASE_DEVELOPMENT_QUEEN_LIFE_SPAN = 10
BASE_DEVELOPMENT_WARRIOR_STRENGTH = 1.2
BASE_DEVELOPMENT_WARRIOR_DEFENSE = 1.5
BASE_DEVELOPMENT_WARRIOR_MAX_HP = 1.5
BASE_DEVELOPMENT_WARRIOR_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_WARRIOR_SPEED = 1
BASE_DEVELOPMENT_WARRIOR_LIFE_SPAN = 1
BASE_DEVELOPMENT_WORKER_STRENGTH = 1
BASE_DEVELOPMENT_WORKER_DEFENSE = 1
BASE_DEVELOPMENT_WORKER_MAX_HP = 1
BASE_DEVELOPMENT_WORKER_HP_REGEN_RATE = 1
BASE_DEVELOPMENT_WORKER_SPEED = 1
BASE_DEVELOPMENT_WORKER_LIFE_SPAN = 1

NEW_SPECIE_MUTATION_PERCENT = 10
NEW_SPECIE_SUPER_MUTATE_CHANCE = 10
NEW_SPECIE_SUPER_MUTATE_PERCENT = 20

MAX_BODY_SIGHT_DISTANCE = 250
MIN_BODY_SIGHT_DISTANCE = 50
MAX_BODY_SPEED = 64
MIN_BODY_SPEED = 10

NEW_EGG_FOOD_COST = 100
LAY_EGG_SEASONS = [SeasonTypes.SUMMER]
EGG_PROGRESS_PER_STEP = 10 #1

LARVA_FEED_PORTION_SIZE = 10 #1
LARVA_REQUIRED_FOOD_QUEEN_MULTIPLIER = 1 #3
LARVA_REQUIRED_FOOD_WARRIOR_MULTIPLIER = 2
LARVA_REQUIRED_FOOD_COMMON_MULTIPLIER = 0.5 #10
