services:
  web:
    image: bugs-backend-image
    build:
      target: backend
      context: .
    command: daphne bugs.asgi:application -b 0.0.0.0 -p 8000
    env_file:
      - bugs/.env.docker
    expose:
      - "8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - database:/app/storage/db/
      - backups:/app/storage/backups/
      - log_files:/app/storage/logs/

  engine:
    image: bugs-backend-image
    command: python engine_start.py
    env_file:
      - bugs/.env.docker
    depends_on:
      - redis
    restart: no
    volumes:
      - log_files:/app/storage/logs/

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: unless-stopped

  caddy:
    build:
      target: caddy_proxie
      context: .
    restart: unless-stopped
    env_file:
      - bugs/.env.docker
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - web
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data

  migrator:
    image: bugs-backend-image
    env_file:
      - bugs/.env.docker
    volumes:
      - database:/app/storage/db/
    command: python manage.py migrate --noinput
    profiles: [migration]

  test:
    image: bugs-backend-image
    env_file:
      - bugs/.env.docker
    command: pytest
    depends_on:
      - redis
    profiles: [test]

volumes:
  database:
  log_files:
  backups:
  caddy_data: