services:
  web:
    image: bugs_app_image:latest
    build: .
    env_file:
      - bugs/.env.docker
    expose:
      - "8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - database:/app/storage/db/
      - backups:/app/storage/backups/
      - log_files:/app/storage/logs/
      - static_files:/app/client/static/

  engine:
    image: bugs_app_image:latest
    command: python engine_start.py
    env_file:
      - bugs/.env.docker
    depends_on:
      - redis
    restart: no
    volumes:
      - log_files:/app/storage/logs/

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    env_file:
      - bugs/.env.docker
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - web
    volumes:
      - ./caddy:/etc/caddy
      - static_files:/static_files
      - caddy_data:/data

  migrator:
    image: bugs_app_image:latest
    env_file:
      - bugs/.env.docker
    volumes:
      - database:/app/storage/db/
    command: python manage.py migrate --noinput
    profiles: [migration]

  test:
    image: bugs_app_image:latest
    env_file:
      - bugs/.env.docker
    command: pytest
    depends_on:
      - redis
    profiles: [test]

volumes:
  database:
  static_files:
  log_files:
  backups:
  caddy_data: