from enum import StrEnum

class ActionTypes(StrEnum):
    ENTITY_BORN = 'entity_born'
    ENTITY_DIED = 'entity_died'
    ENTITY_COLONY_CHANGED = 'entity_colony_changed'
    ENTITY_ROTATED = 'entity_rotated'
    ENTITY_HP_CHANGED = 'entity_hp_change'
    ENTITY_WALK = 'entity_walk'
    ENTITY_GOT_IN_NEST = 'entity_got_in_nest'
    ENTITY_GOT_OUT_OF_NEST = 'entity_got_out_of_nest'
    ANT_PICKED_UP_ITEM = 'ant_picked_up_item'
    ANT_DROPPED_PICKED_ITEM = 'ant_dropped_picked_item'
    ANT_FLEW_NUPTIAL_FLIGHT = 'ant_flew_nuptial_flight'
    NEST_STORED_CALORIES_CHANGED = 'nest_stored_calories_changed'
    NEST_LARVAE_CHANGED = 'nest_larvae_changed'
    NEST_BUILD_STATUS_CHANGED = 'nest_build_status_changed'
    ITEM_WAS_PICKED_UP = 'item_was_picked_up'
    ITEM_WAS_DROPPED = 'item_was_dropped'
    ITEM_BEING_BRINGED = 'item_being_bringed'
    COLONY_BORN = 'colony_born'
    COLONY_OPERATIONS_CHANGED = 'colony_operations_change'