const UI_CONSTS = {
    DOUBLE_CLICK_PROTECT_MS: 2500,
    WORLD_VIEW_FONT_NAME: ['Tahoma', 'Verdana', 'Arial', 'sans-serif'],
    WORLD_VIEW_FONT_SIZE: 14,
    WORLD_VIEW_FONT_COLOR: 0x000000,
    WORLD_VIEW_ANT_STATS_SHOW_TIEM: 10000,
    WORLD_VIEW_NEST_AREA_COLOR: 0xFFFF00,
    WORLD_VIEW_MARKERS_CONNECTOR_COLOR: 0xFF0000,
    INFO_LINE_OPACITY: 0.9,
    INFO_LINE_INSIDE_OPACITY: 0.7,
}

export {
    UI_CONSTS
}