from enum import StrEnum

class ThoughtTypes(StrEnum):
    GO_IN_NEST = 'go_in_nest'
    WALK_TO = 'walk_to'
    RANDOM_WALK = 'random_walk'
    COLLECT_FOOD = 'collect_food'
    FEED_MYSELF = 'feed_myself'
    BUILD_NEST = 'build_nest'
    PATROL_NEST_TERRITORY = 'patrol_nest_territory'
    ATTACK_NEST = 'attack_nest'
    FIGHT_ENEMY = 'fight_enemy'
    FIGHT_NEAR_ENEMIES = 'fight_near_enemies'
    DEFEND_NEST = 'defend_nest'
    DEFEND_COLONY = 'defend_colony'
    DEFEND_MYSELF = 'defend_myself'
    SHELTER_IN_NEST = 'shelter_in_nest'
    HUNT_FOR_APHID = 'hunt_for_aphid'
    KEEP_CLEAR_TERRITORY = 'keep_clear_territory'
    WAIT_STEP = 'wait_step'
    HIBERNATION = 'hibernation'
    LADYBUG_HIBERNATION = 'ladybug_hibernation'
    BUILD_FORTIFICATION = 'build_fortification'