const CONSTS = {
    NEW_EGG_FOOD_COST: null,
    STEPS_IN_YEAR: null,
    SPRING_START_YEAR_STEP: null,
    SUMMER_START_YEAR_STEP: null,
    AUTUMN_START_YEAR_STEP: null,
    WINTER_START_YEAR_STEP: null,
    LAY_EGG_SEASONS: null,
    NUPTIAL_FLIGHT_SEASONS: null,
    MAX_DISTANCE_TO_SUB_NEST: null,
    MAX_SUB_NEST_COUNT: null,
    REQUIRED_GENES: null,
    MAX_DISTANCE_TO_OPERATION_TARGET: null,
    BUILD_NEW_SUB_NEST_OPERATION_REQUIREMENTS: null,
    DESTROY_NEST_OPERATION_REQUIREMENTS: null,
    PILLAGE_NEST_OPERATION_REQUIREMENTS: null,
    TRANSPORT_FOOD_OPERATION_REQUIREMENTS: null,
    BUILD_FORTIFICATION_OPERATION_REQUIREMENTS: null,
    ITEM_SOURCE_BLOCKING_DISTANCE: null
}

function initConts(constsValues) {
    Object.assign(CONSTS, constsValues)
}

export {
    CONSTS,
    initConts
}