"""
Django settings for bugs project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qv!8c)g#2br&@y#0%h557i^tlq)6+g*!4vznz8)vxy0jf3#ve1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'b9d0-37-139-176-92.ngrok-free.app'
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'https://b9d0-37-139-176-92.ngrok-free.app'
]

MAIN_SOCKET_URL = '/mainsocket'

# Application definition

INSTALLED_APPS = [
    'daphne',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'client.apps.ClientConfig',
    'core.apps.CoreConfig',
    'infrastructure.apps.InfrastructureConfig',
    'main.apps.MainConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'infrastructure.middlewares.convertJsonMiddleware.ConvertJSONMiddleware',
    'infrastructure.middlewares.httpRequestErrorsHandlerMiddleware.HttpRequestErrorsHandlerMiddleware'
]

ROOT_URLCONF = 'bugs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bugs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'client/static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'bugs.asgi.application'

AUTH_USER_MODEL = 'infrastructure.User'

LOGIN_URL = '/account'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'game_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'game_errors.log',
            'formatter': 'detailed',
        },
        'game_console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'request_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'request_errors.log',
            'formatter': 'detailed',
        },
    },
    'formatters': {
        'detailed': {
            'format': '%(asctime)s %(levelname)s: %(message)s',
        },
    },
    'loggers': {
        'game_logger': {
            'handlers': ['game_file', 'game_console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'request_logger': {
            'handlers': ['request_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

GOOGLE_CLIENT_ID='722545101653-j1gkkj3s807i5amjpvh51elm0nr4aet2.apps.googleusercontent.com'
# GOOGLE_CLIENT_ID='722545101653-9e6l6u1e85lo4gn723e2srhabq0kdieq.apps.googleusercontent.com'
GOOGLE_OAUTH_REDIRECT_URI = "http://localhost:8000/api/accounts/google_auth_callback"
# GOOGLE_OAUTH_REDIRECT_URI = "https://b9d0-37-139-176-92.ngrok-free.app/api/accounts/google_auth_callback"